version: "2.1"
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.7
workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/go.yml
          mapping: |
            go/*
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/ruby.yml
          mapping: |
            ruby/*
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/ruby.yml
          mapping: |
            scala/*
