version: "2.1"
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.7
workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: main
          mapping: |
            go/* lang "go" .circleci/go.yml
            ruby/* lang "ruby" .circleci/ruby.yml
            scala/* lang "scala" .circleci/scala.yml
