# Config dedicated for the go library
# All the resources must be prefixed with `go-` to avoid conflicts

version: 2.1

parameters:
  lang:
    type: string
    default: "unset"

jobs:
  go-build:
    docker:
      - image: alpine
    steps:
      - common-say-hello:
          from: << pipeline.parameters.lang >>-build

workflows:
  go-workflow:
    jobs:
      - common-pre
      - go-build:
          requires:
            - common-pre
