# Config dedicated for the ruby library
# All the resources must be prefixed with `ruby-` to avoid conflicts

version: 2.1

parameters:
  lang:
    type: string
    default: "unset"

jobs:
  ruby-build:
    docker:
      - image: alpine
    steps:
      - run: echo 'Hello from the << pipeline.parameters.lang >>-build job'

workflows:
  ruby-workflow:
    jobs:
      - ruby-build
