# Config dedicated for the ruby library
# All the resources must be prefixed with `ruby-` to avoid conflicts

version: 2.1

jobs:
  ruby-build:
    # docker:
    #   - image: alpine
    steps:
      - common-say-hello:
          from: ruby-build

workflows:
  ruby-workflow:
    jobs:
      - common-pre
      - ruby-build:
          requires:
            - common-pre
